spring.application.name=backend

# Connection string
spring.datasource.url=jdbc:postgresql://localhost:5432/shazoom_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
