spring.application.name=backend

# ===============================
# Connection string
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/shazoom_db
spring.datasource.username=postgres
spring.datasource.password=0000

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Batch inserts
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

# ===============================
# File uploads
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
